
# the audiomerge profile is optional.. the audio merge workflow should
# use a default, if this encoding profile is not present
profile.audiomerge.work.name = audiomerge
profile.audiomerge.work.input = visual
profile.audiomerge.work.output = visual
profile.audiomerge.work.suffix = -merged.mkv
profile.audiomerge.work.ffmpeg.command = #{audioMergeCommand} \
  -c:a flac \
  #{out.dir}/#{out.name}#{out.suffix}

profile.partial-import-preencode.name = partial-import-preencode
profile.partial-import-preencode.input = audiovisual
profile.partial-import-preencode.output = audiovisual
profile.partial-import-preencode.suffix = -preencoded.mp4
profile.partial-import-preencode.mimetype = video/mp4
profile.partial-import-preencode.ffmpeg.command = -i #{in.video.path} \
  -filter:v scale=1920:-2,fps=30 \
  -shortest -c:v libx264 -pix_fmt yuv420p \
  -c:a aac -b:a 196k \
  -ar 44100 -max_muxing_queue_size 9999 \
  #{out.dir}/#{out.name}#{out.suffix}

profile.concat.work.name = concat
profile.concat.work.input = visual
profile.concat.work.output = visual
profile.concat.work.suffix = -concatenated.mkv
profile.concat.work.ffmpeg.command = #{concatCommand} \
  -c:v libx264 -crf 10 -preset fast \
  -c:a flac \
  #{out.dir}/#{out.name}#{out.suffix}

profile.trim.work.name = trim track
profile.trim.work.input = stream
profile.trim.work.output = visual
profile.trim.work.suffix = -trimmed.#{in.video.suffix}
profile.trim.work.ffmpeg.command = -ss #{trim.start} -i #{in.video.path} -t #{trim.duration} -c copy #{out.dir}/#{out.name}#{out.suffix}

profile.encode.partial-import.name = editor
profile.encode.partial-import.input = audiovisual
profile.encode.partial-import.output = audiovisual
profile.encode.partial-import.suffix = -editor.mp4
profile.encode.partial-import.mimetype = video/mp4
profile.encode.partial-import.ffmpeg.command = -i #{in.video.path} \
  -filter:v crop=trunc(iw/2)*2:trunc(ih/2)*2,fps=25 -shortest -c:v libx264 -preset superfast -pix_fmt yuv420p -crf 18 -c:a aac -b:a 196k \
  #{out.dir}/#{out.name}#{out.suffix}