#!/bin/bash

if [ $# -ne 1 ]; then
  echo "Usage: $0 release"
  echo " eg: $0 17.5 -> downloads the 17.5 allinone release tarball and copies its jars to your ~/.m2 repository"
  exit 1
fi

curl -s -L \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/opencast/opencast/releases/tags/$1 | \
jq -r '.assets[] | select(.name | contains("allinone")) | .browser_download_url' | while read url
do
  echo "Downloading $url"
  curl -LO $url
  tar xzf `basename $url`
  rsync -a ./opencast-dist-allinone/system/org/opencastproject/ ~/.m2/repository/org/opencastproject/
  rm -rf opencast-dist-allinone*
done
